### ISSUE TITLE
Error: : cannot connect to X server 

### ISSUE THREAD

**Issue by changhwanjoe** [Gokathon2018-Alibama/Alibama#1]
gui 가 없는 Linux 환경에서 이미지 등을 띄우려 할 때 발생하는 에러. 
openCV 로 처리된 이미지를 띄울 때 발생. 

![image](https://user-images.githubusercontent.com/13927237/44014968-941a687e-9f09-11e8-9b06-2a077a920b47.png)

**Comment by inyong37** [comment]
:'( then what is the solution?
=> remove ‘imshow()’

**Comment by changhwanjoe** [comment]
GUI를 볼 수 있는 Xming, Xlauncher 등의 X window 시스템을 설치하고, Putty와 연동해서 사용하면 해결됨. 
[Using Xming for X11 applications on an EC2 machine](http://www.full360.com/2008/09/29/using-xming-for-x11-applications-on-an-ec2-machine.html)
